import Head from 'next/head';
import Header from './Header';
import JumpToTop from './JumpToTop';
import Footer from './Footer';

function Layout({ title, children, description }) {
  if (!description)
    description =
      'art, surrealism, writer, story, surrealist art, aran, aran hosseini';

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8"></meta>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Header></Header>
      {children}

      <JumpToTop></JumpToTop>

      <Footer></Footer>
    </div>
  );
}

Layout.defaultProps = {
  title: 'Portfolio',
};

export default Layout;
