import style from '@/styles/Home.module.scss';
import { useRouter } from 'next/router';
import { useEffect, useState, useRef } from 'react';
import Head from 'next/head';
import HomeSvg from '@/svg/homepage.svg';

function About() {
  const router = useRouter();
  const [device, setDevice] = useState('desktop');

  const container = useRef();

  const changeDeviceHandler = (e) => {
    if (window.innerWidth > 500) {
      setDevice('desktop');
    } else {
      setDevice('mobile');
    }
  };

  useEffect(() => {
    const ua = navigator.userAgent;
    if (/(tablet|ipad|playbook|silk)|(android(?!.*mobi))/i.test(ua)) {
      setDevice('tablet');
    } else if (
      /Mobile|Android|iP(hone|od)|IEMobile|BlackBerry|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(
        ua
      )
    ) {
      setDevice('mobile');
    } else {
      setDevice('desktop');
    }

    if (window.innerWidth > 500) {
      setDevice('desktop');
    } else {
      setDevice('mobile');
    }

    window.addEventListener('resize', changeDeviceHandler);

    // remove Haeader from this page
    const pageContainer = container.current.parentElement;
    pageContainer.firstChild.style.display = 'none';
    pageContainer.lastChild.style.display = 'none';
  }, []);

  const onClick = (e) => {
    router.push('/gallery');
  };

  return (
    <div className={style.home} ref={container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8"></meta>
        <meta name="description" content="home page" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <h1>
        a
        <sub onClick={onClick} className={style.sub}>
          {device === 'mobile' ? <HomeSvg /> : <span>&#8709;</span>}
        </sub>
      </h1>
      <p>PRESS ‘NAUGHT’ TO GET IN.</p>
    </div>
  );
}

export default About;
